services:

  app-app:
    build: 
      context: .
      dockerfile: ./docker/php/Dockerfile.php
    volumes:
      - .:/var/www/
    container_name: app
    working_dir: /var/www
    networks:
      - app-network

  webserver:
    image: nginx:alpine
    container_name: app_webserver
    volumes:
      - .:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
      # - "443:443"
    links:
      - app
    networks:
      - app-network
    depends_on:
      - app

networks:
  app-network:
    driver: bridge

volumes:
  app_data:
    driver: local 